Первый review для рогалика
kiwiband/DungeonsAndBacon pull request #1
Opened 2019-03-13 11:15 UTC by kostya55516

- Эвент система
- Движение персонажа
- Система коллизий
- UI
- Генерация карты
- Сохранение и загрузка карты

2019-03-25 22:20 UTC, ArtyomLobanov requested changes
1. Выглядит очень круто. Жду релиза.
2. Где можно найти архитектурную документацию?
3. Добавьте тесты и подключите Travis
4. Ох и любите вы синглтоны.

2019-03-25 22:20 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/InputManager.kt
> +class InputManager(val terminal: Terminal) {
Добавьте комментарии к классам и методам

2019-03-25 22:20 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/actors/MapActor.kt
> +    fun compare(other: ViewOrder): Int = other.order - order
Это уже сделано за вас
>Также enum-константы реализуют интерфейс Comparable. Порядок сортировки соответствует порядку объявления.

[Отсюда](https://kotlinlang.ru/docs/reference/enum-classes.html)

2019-03-25 22:20 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2.kt
> +class Vec2(x: Int, y: Int) : Vec2M(x, y) {
Можно было назвать Point. Всего на один символ длиннее, но при этом уже полноценное слово.

2019-03-25 22:20 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
А как ваше зашифрованное название надо понимать? Что означает буква M?

2019-03-25 22:20 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
И зачем вам Vec2M и Vec2? И почему один наследуется от другого? Если планировалось, что Vec2M неизменяемый, а Vec2 изменяемый, то странно, что один наследник другого.

2019-03-25 23:02 UTC, ArtyomLobanov commented
Я не буду требовать отказаться от синглтонов, но попробую аргументировать, почему их использование может усложнить вам жизнь в будущем.
1. Вложенные контексты. Допустим, в вашей игре появились диалоговые окна. Ну или игрок открыл инвентарь персонажа. На какие клавиши удобно переключать вещи? На те же, на которые двигать персонажа - цфыв или стрелочки. Однако, будет не ловко, если эти нажатия будут восприниматься как попытки передвинуть персонажа. Как это можно исправить? Можно как-нибудь удалять колбеки, а потом возвращать их обратно. Можно насоздавать флагов на все случаи жизни (А не в меню ли мы находимся? А не открыто ли диалоговое окно?) и в обработчиках проверять их состояние. Но если бы диспетчер слушателей событий не был бы синглтоном, можно было бы просто создать новый диспетчер, добавить в него только необходимые колбеки и использовать его, пока игрок находится в меню, а не в игре.
2. Повторная игра. Пользователь играл, играл и устал. Вышел в меню. Что нужно сделать? Удалить все неактуальные колбеки. А как понять, какие актуальные, а какие - нет? Скорее всего с ростом проекта и разномастных обработчиков расплодится целая куча. Причём добавляться они могут из разных частей проекта. И как за всеми уследить? А потом игрок решает опять поиграть. Теперь надо опять добавить колбеки, причём следить, чтобы никакой колбек случайно не был добавлен дважды.
3. Ну и самый вероятный сценарий - пользователь будет играть очень долго и у вас переполнится глобальный генератор идентификаторов обработчиков, а из-за этого сломается последовательность их вызовов.

2019-03-26 10:39 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/math/Vec2.kt
> +class Vec2(x: Int, y: Int) : Vec2M(x, y) {
Они используются как для точек, так и для векторов. Поэтому vec2 - это двумерный математический вектор, а уже способ его использования какой угодно. val direction: Point будет выглядеть странно

2019-03-26 10:43 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
Это не фича, а баг) Вообще они должны называться наоборот, конечно, ибо M - это Mutable.
Наследование - вынужденная мера для полиморфизма, чтобы делать функции, которые точно не изменят значение твоего вектора. Это дает только один плохой сайдэффект, когда мы передаем куда-то изменяемый вектор, как неизменяемый, сохраняем его там, а он потом изменится снаружи. Но я решил, что лучше так оставить, чем всё изменяемым делать.
Это лучше код документирует, по крайней мере

2019-03-26 10:49 UTC, kostya55516 commented
@ArtyomLobanov 
Архитектура лежит в прошлой домашке, ну либо вот копии на момент этого сообщения:
https://docs.google.com/document/d/1DD-9U7wInzVkBt8xA2jl18ygCVNAbpSh3kfoIcpjsw4/edit?usp=sharing
(Чтобы удобнее было смотреть)
 https://drive.google.com/file/d/12FRixYhPET0o5yHM7ExGBFRC1A4hWFHT/view?usp=sharing

2019-03-26 12:18 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
Так а может лучше только неизменяемую версию оставить, а координаты объектов объявлять var, а не val?

2019-03-26 12:31 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
Тогда в любом for, где нам надо будет как-то использовать vec2, будет миллион вызовов new и delete, что очень негативно скажется на скорости работы и количестве выделяемой памяти у разросшегося проекта. Особенно если предположить, что эта штука будет собираться где-нибудь на мобилках или в браузере, где подобные оверхэды на mutable объектах будут очень неприятными

2019-03-26 12:32 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
Тут можно провести аналогию со строковым + и StringBuilder. Второй придумали не просто так, это и правда дает хороший прирост производительности

2019-03-26 12:55 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
У сложения строк через + квадратичная асимптотика по времени, а неизменяемые точки максимум в константу раз время увеличат. Преждевременная оптимизация — корень всех зол.  Если всё же хочется иметь оба класса, то можно посмотреть, как эту проблему решают другие люди. Например, в kotlin есть две параллельных иерархии наследования для мутабельных и немутабельных коллекций. А в Java Collections.unmodifiableList() реализовано через UnmodifiableList, у которого переопределены модифицирующие методы.
```java
        public E get(int index) {return list.get(index);}
        public E set(int index, E element) {
            throw new UnsupportedOperationException();
        }
        public void add(int index, E element) {
            throw new UnsupportedOperationException();
        }
        public E remove(int index) {
            throw new UnsupportedOperationException();
        }
```

2019-03-26 20:05 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
Поправка: не в kotlin, а в scala

2019-04-09 14:17 UTC, Geckostya commented on src/main/kotlin/kiwiband/dnb/math/Vec2M.kt
> +open class Vec2M(var x: Int, var y: Int) {
в Kotlin MutableCollection : Collection, так что аргумент про других людей не очень работает. Альтернатива этому методу всё же сделать всё Mutable, но так будет хуже, ибо это никак код не документирует в функциях, где нужно получить вектор и не менять его, именно для такого и было сделано наследование

2019-06-02 11:40 UTC, ArtyomLobanov reviewed
Пожалуйста, перенесите исправления в основную ветку разработки игры и сделайте из неё пул-реквест в пустую ветку. Для удобства, в дальнейшем проверять и исправлять будем её одну, а не отдельные ветки для каждого этапа.

2019-06-02 11:40 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/math/Vec2.kt
> +open class Vec2(var x: Int, var y: Int) {
Хотите фокус с вашим "Immutable" классом Vec2?
```kotlin
val v = Vec2(1, 2)
v.x = 4
print(v.x)
```
```
4
```
По умолчанию свойства (property) имею видимость public. Объявите их как val, либо сделайте сеттер приватным.

2019-06-02 11:40 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/map/MapSaver.kt
> +    fun saveToFile(map: LocalMap, filename: String) {
Тут комментарий пропустили

2019-06-02 11:40 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/map/LocalMap.kt
> +            dungeonGenerator.randomConnectorChance = 0.01f
Магические константы

2019-06-02 12:21 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/map/MapSaver.kt
> +    fun saveToFile(map: LocalMap, filename: String) {
MapSaver saveToFile(map, filename)
Действительно, что же делает этот метод?
Если нет цели генерировать красивую html страничку с документацией, то документация таких вот методов ухудшает читаемость кода, притом значительно, а пользы абсолютно никакой.
Это не библиотека и не API, если тут люди будут разбираться в коде и как-то с ним работать, то с помощью самого кода. Так что нет никакого смысла в документировании каждого чиха

2019-06-02 12:31 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/map/LocalMap.kt
> +            dungeonGenerator.randomConnectorChance = 0.01f
object DungeonGeneratorContatns {
	val MAX_ROOM_SIZE = 11
	val MIN_ROOM_SIZE = 5
	val WINDING_CHANCE = 0
	val RANDOM_CONNECTOR_CHANCE = 0.01F
}

dungeonGenerator.maxRoomSize = DungeonGeneratorContatns.MAX_ROOM_SIZE 
dungeonGenerator.minRoomSize = DungeonGeneratorContatns.MIN_ROOM_SIZE 
dungeonGenerator.windingChance = DungeonGeneratorContatns.WINDING_CHANCE 
dungeonGenerator.randomConnectorChance = DungeonGeneratorContatns.RANDOM_CONNECTOR_CHANCE 

Да, так намного лучше, сразу понятно стало, что они делают.
Ладно, извиняюсь за желчь, просто серьезно здесь нет никакой необходимости в этом. Если в проекте появится два генератора данжей и у них будет что-то пересекаться, то это будет иметь хоть какой-то смысл, а пока это больше похоже не на хороший рефакторинг на будущее, а на обфускацию.
Магические константы имеет смысл называть, несмотря ни на что, если у них нет названия, а тут мы четко заполняем понятные переменные

2019-06-02 12:32 UTC, kostya55516 commented on src/main/kotlin/kiwiband/dnb/map/LocalMap.kt
> +            dungeonGenerator.randomConnectorChance = 0.01f
> Contatns
пара очепяток в слове

2019-06-02 12:34 UTC, ArtyomLobanov commented on src/main/kotlin/kiwiband/dnb/map/MapSaver.kt
> +    fun saveToFile(map: LocalMap, filename: String) {
>документация таких вот методов ухудшает читаемость кода, притом значительно

Спорно.
Комментарии нужны не только для того, чтобы описать ЧТО делает метод, но и КАК. Да, наверное, этот метод сохраняет карту в файл. Но что, если файл уже существовал? Что, если существовала папка с таким именем?
Это учебный проект. Некоторые вещи тут могут казаться избыточными - это нормально.

2019-06-17 09:07 UTC, vasyoid commented
@ArtyomLobanov 
> Пожалуйста, перенесите исправления в основную ветку разработки игры и сделайте из неё пул-реквест в пустую ветку. Для удобства, в дальнейшем проверять и исправлять будем её одну, а не отдельные ветки для каждого этапа.

Можно проверять только последний PR (#4). В нем есть все исправления, которые мы сделали и всё что касается всех заданий

2019-06-29 15:56 UTC, closed without merging